config/routes.rb
Rails.application.routes.draw do
  resources :buckets
  resources :distributions

  root 'distributions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  def index
    s3 ||=  Aws::S3::Client.new
    @buckets = s3.list_buckets.buckets.map(&:name) 
  end

  def show
    @distribution_alias = params[:distribution_alias]
    @bucket = params[:id]
    delimiter = params[:delimiter] || '/'
    prefix = params[:prefix] || nil

    s3 ||=  Aws::S3::Client.new
	resp = s3.list_objects(bucket: @bucket, delimiter: delimiter, prefix: prefix, max_keys: 500000)
	@prefixes = resp.common_prefixes.map(&:prefix)
	@keys = resp.contents.sort!{| a, b | b[:last_modified] <=> a[:last_modified] }.map(&:key) - [ prefix ] 
  end
end

app/controllers/distributions_controller.rb
class DistributionsController < ApplicationController
  def index
    cloudfront ||=  Aws::CloudFront::Client.new
    @distributions = [] 
    cloudfront.list_distributions.distribution_list.items.each do |e|
      @distributions << { 
        id: e.id, 
	aliases: e.aliases.items, 
	bucket: e.origins.items.first.domain_name.split('.s3.amazonaws.com') }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buckets/index.html.erb
<h1>s3 buckets</h1>

<% @buckets.each do |e| %>
  <h2><%= link_to e, bucket_path(e) %></h2> 
<% end %>

app/views/buckets/show.html.erb
<h1><%= @bucket %></h1>

<% @prefixes.each do |p| %>
  <p><%= link_to p, bucket_path(@bucket, prefix: p, distribution_alias: @distribution_alias) %></p>
<% end %>

<% @keys.each_with_index do |k| %>
  <p>
    <%= link_to k,
        "#{'https://' + @distribution_alias + '/' + CGI.escape(k)}"
    %>
    <button class="clipboard-btn btn btn-default btn-xs" data-clipboard-action="copy" data-clipboard-text= <%= "#{'https://' + @distribution_alias + '/' + CGI.escape(k)}" %>>
      Copier le lien
    </button>
  </p>
<% end %>

app/views/distributions/index.html.erb
<h1>Distributions</h1>

<% @distributions.each do |e| %>
  <h2><%= link_to e[:aliases].join(', '), bucket_path(e[:bucket], distribution_alias: e[:aliases].first)  %></h2> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>S3CfBrowser</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>